// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1SmfRjLFI0k_rXdLS8vmoQhFPASnxP0',
    appId: '1:314449605310:web:b05cfa4cb6781a9442a4ef',
    messagingSenderId: '314449605310',
    projectId: 'testapp-7cf63',
    authDomain: 'testapp-7cf63.firebaseapp.com',
    storageBucket: 'testapp-7cf63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7xSsJpLb1KVOime9reEKmLR8KEFYqeh8',
    appId: '1:314449605310:android:f682cafac07baeaf42a4ef',
    messagingSenderId: '314449605310',
    projectId: 'testapp-7cf63',
    storageBucket: 'testapp-7cf63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0cKVNS-ENdRfd1tyn9pXlWcoDiwS_29w',
    appId: '1:314449605310:ios:9671dac1182d48bd42a4ef',
    messagingSenderId: '314449605310',
    projectId: 'testapp-7cf63',
    storageBucket: 'testapp-7cf63.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0cKVNS-ENdRfd1tyn9pXlWcoDiwS_29w',
    appId: '1:314449605310:ios:a31251fb0eaf7a3142a4ef',
    messagingSenderId: '314449605310',
    projectId: 'testapp-7cf63',
    storageBucket: 'testapp-7cf63.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
